export const mailConstants = {
    GETMAILS_REQUEST: "GETMAILS_REQUEST",
    GETMAILS_SUCCESS: "GETMAILS_SUCCESS",
    GETMAILS_FAILURE: "GETMAILS_FAILURE",

    GETMAIL_REQUEST: "GETMAIL_REQUEST",
    GETMAIL_SUCCESS: "GETMAIL_SUCCESS",
    GETMAIL_FAILURE: "GETMAIL_FAILURE",

    DELETEMAIL_REQUEST: "DELETEMAIL_REQUEST",
    DELETEMAIL_SUCCESS: "DELETEMAIL_SUCCESS",
    DELETEMAIL_FAILURE: "DELETEMAIL_FAILURE",

    CREATEMAIL_REQUEST: "CREATEMAIL_REQUEST",
    CREATEMAIL_SUCCESS: "CREATEMAIL_SUCCESS",
    CREATEMAIL_FAILURE: "CREATEMAIL_FAILURE",

    UPDATEMAIL_REQUEST: "UPDATEMAIL_REQUEST",
    UPDATEMAIL_SUCCESS: "UPDATEMAIL_SUCCESS",
    UPDATEMAIL_FAILURE: "UPDATEMAIL_FAILURE",

    GETMAILTYPES_REQUEST: "GETMAILTYPES_REQUEST",
    GETMAILTYPES_SUCCESS: "GETMAILTYPES_SUCCESS",
    GETMAILTYPES_FAILURE: "GETMAILTYPES_FAILURE",

    GETMAILTYPE_REQUEST: "GETMAILTYPE_REQUEST",
    GETMAILTYPE_SUCCESS: "GETMAILTYPE_SUCCESS",
    GETMAILTYPE_FAILURE: "GETMAILTYPE_FAILURE",

    DELETEMAILTYPE_REQUEST: "DELETEMAILTYPE_REQUEST",
    DELETEMAILTYPE_SUCCESS: "DELETEMAILTYPE_SUCCESS",
    DELETEMAILTYPE_FAILURE: "DELETEMAILTYPE_FAILURE",

    CREATEMAILTYPE_REQUEST: "CREATEMAILTYPE_REQUEST",
    CREATEMAILTYPE_SUCCESS: "CREATEMAILTYPE_SUCCESS",
    CREATEMAILTYPE_FAILURE: "CREATEMAILTYPE_FAILURE",

    UPDATEMAILTYPE_REQUEST: "UPDATEMAILTYPE_REQUEST",
    UPDATEMAILTYPE_SUCCESS: "UPDATEMAILTYPE_SUCCESS",
    UPDATEMAILTYPE_FAILURE: "UPDATEMAILTYPE_FAILURE",
}