export const searchConstants = {
    SEARCHAPPRETICE_REQUEST: "SEARCHAPPRETICE_REQUEST",
    SEARCHAPPRETICE_SUCCESS: "SEARCHAPPRETICE_SUCCESS",
    SEARCHAPPRETICE_FAILURE: "SEARCHAPPRETICE_FAILURE"
}