export const solicityConstants = {
    GETSOLICITYDRAW_REQUEST: "GETSOLICITYDRAW_REQUEST",
    GETSOLICITYDRAW_SUCCESS: "GETSOLICITYDRAW_SUCCESS",
    GETSOLICITYDRAW_FAILURE: "GETSOLICITYDRAW_FAILURE",

    GETSOLICITIES_REQUEST: "GETSOLICITIES_REQUEST",
    GETSOLICITIES_SUCCESS: "GETSOLICITIES_SUCCESS",
    GETSOLICITIES_FAILURE: "GETSOLICITIES_FAILURE",

    SAVESOLICITY_REQUEST: "SAVESOLICITY_REQUEST",
    SAVESOLICITY_SUCCESS: "SAVESOLICITY_SUCCESS",
    SAVESOLICITY_FAILURE: "SAVESOLICITY_FAILURE",
    SAVESOLICITY_FINISH: "SAVESOLICITY_FINISH",

    GETMOTIVESORPROHIBITIONS_REQUEST: "GETMOTIVESORPROHIBITIONS_REQUEST",
    GETMOTIVESORPROHIBITIONS_SUCCESS: "GETMOTIVESORPROHIBITIONS_SUCCESS",
    GETMOTIVESORPROHIBITIONS_FAILURE: "GETMOTIVESORPROHIBITIONS_FAILURE",

    SAVEMOTIVESORPROHIBITIONS_REQUEST: "SAVEMOTIVESORPROHIBITIONS_REQUEST",
    SAVEMOTIVESORPROHIBITIONS_SUCCESS: "SAVEMOTIVESORPROHIBITIONS_SUCCESS",
    SAVEMOTIVESORPROHIBITIONS_FAILURE: "SAVEMOTIVESORPROHIBITIONS_FAILURE",

    SAVEMOTIVESORPROHIBITIONS_FINISH: "SAVEMOTIVESORPROHIBITIONS_FINISH",
}