export const solicityConstants = {
    GETSOLICITYDRAW_REQUEST: "GETSOLICITYDRAW_REQUEST",
    GETSOLICITYDRAW_SUCCESS: "GETSOLICITYDRAW_SUCCESS",
    GETSOLICITYDRAW_FAILURE: "GETSOLICITYDRAW_FAILURE",

    GETMOTIVESORPROHIBITIONS_REQUEST: "GETMOTIVESORPROHIBITIONS_REQUEST",
    GETMOTIVESORPROHIBITIONS_SUCCESS: "GETMOTIVESORPROHIBITIONS_SUCCESS",
    GETMOTIVESORPROHIBITIONS_FAILURE: "GETMOTIVESORPROHIBITIONS_FAILURE",

    SAVEMOTIVESORPROHIBITIONS_REQUEST: "SAVEMOTIVESORPROHIBITIONS_REQUEST",
    SAVEMOTIVESORPROHIBITIONS_SUCCESS: "SAVEMOTIVESORPROHIBITIONS_SUCCESS",
    SAVEMOTIVESORPROHIBITIONS_FAILURE: "SAVEMOTIVESORPROHIBITIONS_FAILURE",
    SAVEMOTIVESORPROHIBITIONS_FINISH: "SAVEMOTIVESORPROHIBITIONS_FINISH",
}