export const solicityConstants = {
    GETSOLICITYDRAW_REQUEST: "GETSOLICITYDRAW_REQUEST",
    GETSOLICITYDRAW_SUCCESS: "GETSOLICITYDRAW_SUCCESS",
    GETSOLICITYDRAW_FAILURE: "GETSOLICITYDRAW_FAILURE",
}