export const templateConstants = {
    GETCUSTOMFIELDS_REQUEST: "GETCUSTOMFIELDS_REQUEST",
    GETCUSTOMFIELDS_SUCCESS: "GETCUSTOMFIELDS_SUCCESS",
    GETCUSTOMFIELDS_FAILURE: "GETCUSTOMFIELDS_FAILURE",

    CREATETEMPLATE_REQUEST: "CREATETEMPLATE_REQUEST",
    CREATETEMPLATE_SUCCESS: "CREATETEMPLATE_SUCCESS",
    CREATETEMPLATE_FAILURE: "CREATETEMPLATE_FAILURE",
    FINISH_CREATE_TEMPLATE: "FINISH_CREATE_TEMPLATE",

    GETTEMPLATES_REQUEST: "GETTEMPLATES_REQUEST",
    GETTEMPLATES_SUCCESS: "GETTEMPLATES_SUCCESS",
    GETTEMPLATES_FAILURE: "GETTEMPLATES_FAILURE",

    SHOWMODAL: "SHOWMODAL",
    HIDEMODAL: "HIDEMODAL",
}